#!/usr/bin/python
import sys, os, subprocess, time, platform, ConfigParser, fcntl, thread, getopt
from observer_common import *

def observer_start():
    client_socket, cmd_str = client_socket_cmd_name() 
    ret, msg = client_start_cmd(client_socket, cmd_str)
    if not ret:
        log_error('%s' % msg)
        client_socket.close()
        sys.exit(1)
    else:
        log_info('start success.')
    time.sleep(1)
    ret, msg = client_cmd_status(client_socket, cmd_str)
    if not ret or msg == definition.G_STOP_STATUS:
        log_info('notice: the process is stopped.')
    else:
        log_info('the programme is running.')
    client_socket.close()

if __name__ == '__main__':
    observer_start()
