#!/usr/bin/python
import sys, os, subprocess, time, platform, ConfigParser, fcntl, thread, getopt
from observer_common import *

def observer_stop():
    client_socket, cmd_str = client_socket_cmd_name() 
    ret, msg = client_stop_cmd(client_socket, cmd_str)
    if not ret:
        log_error('%s' % msg)
        client_socket.close()
        sys.exit(1)
    else:
        log_info('stop success.')

if __name__ == '__main__':
    observer_stop()
